export type Airport = {
  code: string;
  city: string;
  name: string;
  country: string;
};

export const AIRPORTS: Airport[] = [
  { code: "ALG", city: "Alger", name: "Aéroport international Houari Boumediene", country: "Algérie" },
  { code: "ORN", city: "Oran", name: "Aéroport international Ahmed Ben Bella", country: "Algérie" },
  { code: "CZL", city: "Constantine", name: "Aéroport international Mohamed Boudiaf", country: "Algérie" },
  { code: "AAE", city: "Annaba", name: "Aéroport Rabah Bitat", country: "Algérie" },
  { code: "BJA", city: "Béjaïa", name: "Aéroport Soummam - Abane Ramdane", country: "Algérie" },
  { code: "BSK", city: "Biskra", name: "Aéroport Mohamed Khider", country: "Algérie" },
  { code: "TLM", city: "Tlemcen", name: "Aéroport Zenata - Messali El Hadj", country: "Algérie" },
  { code: "GHA", city: "Ghardaïa", name: "Aéroport Noumérat - Moufdi Zakaria", country: "Algérie" },
  { code: "HME", city: "Hassi Messaoud", name: "Aéroport Oued Irara - Krim Belkacem", country: "Algérie" },
  { code: "TMR", city: "Tamanrasset", name: "Aéroport Aguenar - Hadj Bey Akhamok", country: "Algérie" },
  { code: "ELU", city: "El Oued", name: "Aéroport Guemar", country: "Algérie" },
  { code: "BLJ", city: "Batna", name: "Aéroport Mostépha Ben Boulaïd", country: "Algérie" },
  { code: "DJG", city: "Djanet", name: "Aéroport Tiska", country: "Algérie" },
  { code: "VVZ", city: "Illizi", name: "Aéroport Takhamalt", country: "Algérie" },
  { code: "CBH", city: "Béchar", name: "Aéroport Boudghene Ben Ali Lotfi", country: "Algérie" },
  { code: "TUN", city: "Tunis", name: "Aéroport international de Tunis-Carthage", country: "Tunisie" },
  { code: "MIR", city: "Monastir", name: "Aéroport international Habib Bourguiba", country: "Tunisie" },
  { code: "DJE", city: "Djerba", name: "Aéroport international de Djerba-Zarzis", country: "Tunisie" },
  { code: "NBE", city: "Enfidha", name: "Aéroport international d’Enfidha-Hammamet", country: "Tunisie" },
  { code: "SFA", city: "Sfax", name: "Aéroport international de Sfax-Thyna", country: "Tunisie" },
  { code: "TOE", city: "Tozeur", name: "Aéroport international de Tozeur-Nefta", country: "Tunisie" },
  { code: "TBJ", city: "Tabarka", name: "Aéroport international de Tabarka-Aïn Draham", country: "Tunisie" },
  { code: "CAI", city: "Le Caire", name: "Aéroport international du Caire", country: "Égypte" },
  { code: "SPX", city: "Le Caire", name: "Aéroport international Sphinx", country: "Égypte" },
  { code: "HRG", city: "Hurghada", name: "Aéroport international de Hurghada", country: "Égypte" },
  { code: "SSH", city: "Charm el-Cheikh", name: "Aéroport international de Charm el-Cheikh", country: "Égypte" },
  { code: "LXR", city: "Louxor", name: "Aéroport international de Louxor", country: "Égypte" },
  { code: "ASW", city: "Assouan", name: "Aéroport international d’Assouan", country: "Égypte" },
  { code: "HBE", city: "Alexandrie", name: "Aéroport international Borg El Arab", country: "Égypte" },
  { code: "RMF", city: "Marsa Alam", name: "Aéroport international de Marsa Alam", country: "Égypte" },
  { code: "CMN", city: "Casablanca", name: "Aéroport international Mohammed V", country: "Maroc" },
  { code: "RAK", city: "Marrakech", name: "Aéroport Marrakech-Ménara", country: "Maroc" },
  { code: "RBA", city: "Rabat", name: "Aéroport Rabat-Salé", country: "Maroc" },
  { code: "AGA", city: "Agadir", name: "Aéroport Agadir-Al Massira", country: "Maroc" },
  { code: "FEZ", city: "Fès", name: "Aéroport Fès-Saïss", country: "Maroc" },
  { code: "TNG", city: "Tanger", name: "Aéroport Tanger-Ibn Battouta", country: "Maroc" },
  { code: "OUD", city: "Oujda", name: "Aéroport Oujda-Angads", country: "Maroc" },
  { code: "NDR", city: "Nador", name: "Aéroport Nador-Al Aroui", country: "Maroc" },
  { code: "TTU", city: "Tétouan", name: "Aéroport Tétouan-Sania R’mel", country: "Maroc" },
  { code: "ESU", city: "Essaouira", name: "Aéroport Essaouira-Mogador", country: "Maroc" },
  { code: "JFK", city: "New York", name: "John F. Kennedy International Airport", country: "États-Unis" },
  { code: "LGA", city: "New York", name: "LaGuardia Airport", country: "États-Unis" },
  { code: "EWR", city: "Newark / New York", name: "Newark Liberty International Airport", country: "États-Unis" },
  { code: "LAX", city: "Los Angeles", name: "Los Angeles International Airport", country: "États-Unis" },
  { code: "SFO", city: "San Francisco", name: "San Francisco International Airport", country: "États-Unis" },
  { code: "ORD", city: "Chicago", name: "O’Hare International Airport", country: "États-Unis" },
  { code: "MDW", city: "Chicago", name: "Midway International Airport", country: "États-Unis" },
  { code: "MIA", city: "Miami", name: "Miami International Airport", country: "États-Unis" },
  { code: "FLL", city: "Fort Lauderdale", name: "Fort Lauderdale-Hollywood International Airport", country: "États-Unis" },
  { code: "ATL", city: "Atlanta", name: "Hartsfield-Jackson Atlanta International Airport", country: "États-Unis" },
  { code: "DFW", city: "Dallas", name: "Dallas/Fort Worth International Airport", country: "États-Unis" },
  { code: "IAH", city: "Houston", name: "George Bush Intercontinental Airport", country: "États-Unis" },
  { code: "BOS", city: "Boston", name: "Logan International Airport", country: "États-Unis" },
  { code: "IAD", city: "Washington", name: "Washington Dulles International Airport", country: "États-Unis" },
  { code: "DCA", city: "Washington", name: "Ronald Reagan Washington National Airport", country: "États-Unis" },
  { code: "SEA", city: "Seattle", name: "Seattle-Tacoma International Airport", country: "États-Unis" },
  { code: "LAS", city: "Las Vegas", name: "Harry Reid International Airport", country: "États-Unis" },
  { code: "MCO", city: "Orlando", name: "Orlando International Airport", country: "États-Unis" },
  { code: "PHX", city: "Phoenix", name: "Phoenix Sky Harbor International Airport", country: "États-Unis" },
  { code: "DEN", city: "Denver", name: "Denver International Airport", country: "États-Unis" },
  { code: "YYZ", city: "Toronto", name: "Toronto Pearson International Airport", country: "Canada" },
  { code: "YTZ", city: "Toronto", name: "Billy Bishop Toronto City Airport", country: "Canada" },
  { code: "YUL", city: "Montréal", name: "Aéroport international Montréal-Trudeau", country: "Canada" },
  { code: "YVR", city: "Vancouver", name: "Vancouver International Airport", country: "Canada" },
  { code: "YYC", city: "Calgary", name: "Calgary International Airport", country: "Canada" },
  { code: "YOW", city: "Ottawa", name: "Ottawa International Airport", country: "Canada" },
  { code: "YEG", city: "Edmonton", name: "Edmonton International Airport", country: "Canada" },
  { code: "YHZ", city: "Halifax", name: "Halifax Stanfield International Airport", country: "Canada" },
  { code: "YWG", city: "Winnipeg", name: "Winnipeg James Armstrong Richardson International Airport", country: "Canada" },
  { code: "YQB", city: "Québec", name: "Aéroport international Jean-Lesage de Québec", country: "Canada" },
  { code: "CDG", city: "Paris", name: "Aéroport Paris-Charles de Gaulle", country: "France" },
  { code: "ORY", city: "Paris", name: "Aéroport Paris-Orly", country: "France" },
  { code: "BVA", city: "Paris / Beauvais", name: "Aéroport Paris-Beauvais", country: "France" },
  { code: "NCE", city: "Nice", name: "Aéroport Nice Côte d’Azur", country: "France" },
  { code: "LYS", city: "Lyon", name: "Aéroport Lyon-Saint Exupéry", country: "France" },
  { code: "MRS", city: "Marseille", name: "Aéroport Marseille-Provence", country: "France" },
  { code: "TLS", city: "Toulouse", name: "Aéroport Toulouse-Blagnac", country: "France" },
  { code: "BOD", city: "Bordeaux", name: "Aéroport Bordeaux-Mérignac", country: "France" },
  { code: "NTE", city: "Nantes", name: "Aéroport Nantes Atlantique", country: "France" },
  { code: "LIL", city: "Lille", name: "Aéroport de Lille", country: "France" },
  { code: "SXB", city: "Strasbourg", name: "Aéroport de Strasbourg", country: "France" },
  { code: "MPL", city: "Montpellier", name: "Aéroport Montpellier-Méditerranée", country: "France" },
  { code: "FRA", city: "Francfort", name: "Frankfurt Airport", country: "Allemagne" },
  { code: "MUC", city: "Munich", name: "Munich Airport", country: "Allemagne" },
  { code: "BER", city: "Berlin", name: "Berlin Brandenburg Airport", country: "Allemagne" },
  { code: "DUS", city: "Düsseldorf", name: "Düsseldorf Airport", country: "Allemagne" },
  { code: "HAM", city: "Hambourg", name: "Hamburg Airport", country: "Allemagne" },
  { code: "CGN", city: "Cologne / Bonn", name: "Cologne Bonn Airport", country: "Allemagne" },
  { code: "STR", city: "Stuttgart", name: "Stuttgart Airport", country: "Allemagne" },
  { code: "HAJ", city: "Hanovre", name: "Hannover Airport", country: "Allemagne" },
  { code: "NUE", city: "Nuremberg", name: "Nuremberg Airport", country: "Allemagne" },
  { code: "LEJ", city: "Leipzig", name: "Leipzig/Halle Airport", country: "Allemagne" },
  { code: "LHR", city: "Londres", name: "London Heathrow Airport", country: "Royaume-Uni" },
  { code: "LGW", city: "Londres", name: "London Gatwick Airport", country: "Royaume-Uni" },
  { code: "STN", city: "Londres", name: "London Stansted Airport", country: "Royaume-Uni" },
  { code: "LTN", city: "Londres", name: "London Luton Airport", country: "Royaume-Uni" },
  { code: "LCY", city: "Londres", name: "London City Airport", country: "Royaume-Uni" },
  { code: "MAN", city: "Manchester", name: "Manchester Airport", country: "Royaume-Uni" },
  { code: "BHX", city: "Birmingham", name: "Birmingham Airport", country: "Royaume-Uni" },
  { code: "EDI", city: "Édimbourg", name: "Edinburgh Airport", country: "Royaume-Uni" },
  { code: "GLA", city: "Glasgow", name: "Glasgow Airport", country: "Royaume-Uni" },
  { code: "BRS", city: "Bristol", name: "Bristol Airport", country: "Royaume-Uni" },
  { code: "FCO", city: "Rome", name: "Aéroport Léonard-de-Vinci de Rome Fiumicino", country: "Italie" },
  { code: "CIA", city: "Rome", name: "Aéroport de Rome Ciampino", country: "Italie" },
  { code: "MXP", city: "Milan", name: "Aéroport de Milan Malpensa", country: "Italie" },
  { code: "LIN", city: "Milan", name: "Aéroport de Milan Linate", country: "Italie" },
  { code: "BGY", city: "Milan / Bergame", name: "Aéroport de Bergame-Orio al Serio", country: "Italie" },
  { code: "VCE", city: "Venise", name: "Aéroport de Venise-Marco Polo", country: "Italie" },
  { code: "NAP", city: "Naples", name: "Aéroport international de Naples", country: "Italie" },
  { code: "BLQ", city: "Bologne", name: "Aéroport de Bologne-Borgo Panigale", country: "Italie" },
  { code: "CTA", city: "Catane", name: "Aéroport de Catane-Fontanarossa", country: "Italie" },
  { code: "PMO", city: "Palerme", name: "Aéroport de Palerme Falcone-Borsellino", country: "Italie" },
  { code: "PSA", city: "Pise", name: "Aéroport international Galileo-Galilei de Pise", country: "Italie" },
  { code: "FLR", city: "Florence", name: "Aéroport de Florence-Peretola", country: "Italie" },
  { code: "MAD", city: "Madrid", name: "Aéroport Adolfo-Suárez Madrid-Barajas", country: "Espagne" },
  { code: "BCN", city: "Barcelone", name: "Aéroport Josep Tarradellas Barcelone-El Prat", country: "Espagne" },
  { code: "AGP", city: "Málaga", name: "Aéroport de Málaga-Costa del Sol", country: "Espagne" },
  { code: "PMI", city: "Palma de Majorque", name: "Aéroport de Palma de Majorque", country: "Espagne" },
  { code: "ALC", city: "Alicante", name: "Aéroport d’Alicante-Elche Miguel Hernández", country: "Espagne" },
  { code: "VLC", city: "Valence", name: "Aéroport de Valence", country: "Espagne" },
  { code: "SVQ", city: "Séville", name: "Aéroport de Séville", country: "Espagne" },
  { code: "BIO", city: "Bilbao", name: "Aéroport de Bilbao", country: "Espagne" },
  { code: "IBZ", city: "Ibiza", name: "Aéroport d’Ibiza", country: "Espagne" },
  { code: "TFS", city: "Tenerife", name: "Aéroport de Tenerife Sud", country: "Espagne" },
  { code: "LPA", city: "Las Palmas", name: "Aéroport de Grande Canarie", country: "Espagne" },
  { code: "BRU", city: "Bruxelles", name: "Aéroport de Bruxelles-National", country: "Belgique" },
  { code: "CRL", city: "Bruxelles / Charleroi", name: "Aéroport de Charleroi Bruxelles-Sud", country: "Belgique" },
  { code: "ANR", city: "Anvers", name: "Aéroport international d’Anvers", country: "Belgique" },
  { code: "OST", city: "Ostende", name: "Aéroport international d’Ostende-Bruges", country: "Belgique" },
  { code: "AMS", city: "Amsterdam", name: "Amsterdam Airport Schiphol", country: "Pays-Bas" },
  { code: "EIN", city: "Eindhoven", name: "Eindhoven Airport", country: "Pays-Bas" },
  { code: "RTM", city: "Rotterdam", name: "Rotterdam The Hague Airport", country: "Pays-Bas" },
  { code: "MST", city: "Maastricht", name: "Maastricht Aachen Airport", country: "Pays-Bas" },
  { code: "IST", city: "Istanbul", name: "Istanbul Airport", country: "Turquie" },
  { code: "SAW", city: "Istanbul", name: "Sabiha Gökçen International Airport", country: "Turquie" },
  { code: "AYT", city: "Antalya", name: "Antalya Airport", country: "Turquie" },
  { code: "ESB", city: "Ankara", name: "Esenboğa International Airport", country: "Turquie" },
  { code: "ADB", city: "Izmir", name: "Adnan Menderes Airport", country: "Turquie" },
  { code: "DLM", city: "Dalaman", name: "Dalaman Airport", country: "Turquie" },
  { code: "BJV", city: "Bodrum", name: "Milas-Bodrum Airport", country: "Turquie" },
  { code: "TZX", city: "Trabzon", name: "Trabzon Airport", country: "Turquie" },
  { code: "ASR", city: "Kayseri", name: "Kayseri Erkilet Airport", country: "Turquie" },
  { code: "GZT", city: "Gaziantep", name: "Gaziantep Airport", country: "Turquie" },
  { code: "NAV", city: "Nevşehir", name: "Nevşehir Kapadokya Airport", country: "Turquie" },
  { code: "SVO", city: "Moscou", name: "Sheremetyevo International Airport", country: "Russie" },
  { code: "DME", city: "Moscou", name: "Domodedovo International Airport", country: "Russie" },
  { code: "VKO", city: "Moscou", name: "Vnukovo International Airport", country: "Russie" },
  { code: "LED", city: "Saint-Pétersbourg", name: "Pulkovo Airport", country: "Russie" },
  { code: "AER", city: "Sotchi", name: "Sochi International Airport", country: "Russie" },
  { code: "KZN", city: "Kazan", name: "Kazan International Airport", country: "Russie" },
  { code: "SVX", city: "Iekaterinbourg", name: "Koltsovo International Airport", country: "Russie" },
  { code: "OVB", city: "Novossibirsk", name: "Tolmachevo Airport", country: "Russie" },
  { code: "UFA", city: "Oufa", name: "Ufa International Airport", country: "Russie" },
  { code: "KRR", city: "Krasnodar", name: "Krasnodar International Airport", country: "Russie" },
  { code: "DXB", city: "Dubaï", name: "Dubai International Airport", country: "Émirats arabes unis" },
  { code: "DWC", city: "Dubaï", name: "Al Maktoum International Airport", country: "Émirats arabes unis" },
  { code: "AUH", city: "Abou Dabi", name: "Zayed International Airport", country: "Émirats arabes unis" },
  { code: "SHJ", city: "Charjah", name: "Sharjah International Airport", country: "Émirats arabes unis" },
  { code: "RKT", city: "Ras Al Khaimah", name: "Ras Al Khaimah International Airport", country: "Émirats arabes unis" },
  { code: "JED", city: "Djeddah", name: "King Abdulaziz International Airport", country: "Arabie saoudite" },
  { code: "RUH", city: "Riyad", name: "King Khalid International Airport", country: "Arabie saoudite" },
  { code: "MED", city: "Médine", name: "Prince Mohammad bin Abdulaziz International Airport", country: "Arabie saoudite" },
  { code: "DMM", city: "Dammam", name: "King Fahd International Airport", country: "Arabie saoudite" },
  { code: "AHB", city: "Abha", name: "Abha International Airport", country: "Arabie saoudite" },
  { code: "TIF", city: "Taïf", name: "Taif International Airport", country: "Arabie saoudite" },
  { code: "ELQ", city: "Al Qassim", name: "Prince Naif bin Abdulaziz International Airport", country: "Arabie saoudite" },
  { code: "YNB", city: "Yanbu", name: "Prince Abdul Mohsin bin Abdulaziz International Airport", country: "Arabie saoudite" },
  { code: "DOH", city: "Doha", name: "Hamad International Airport", country: "Qatar" },
  { code: "AMM", city: "Amman", name: "Queen Alia International Airport", country: "Jordanie" },
  { code: "AQJ", city: "Aqaba", name: "King Hussein International Airport", country: "Jordanie" },
  { code: "PEK", city: "Pékin", name: "Beijing Capital International Airport", country: "Chine" },
  { code: "PKX", city: "Pékin", name: "Beijing Daxing International Airport", country: "Chine" },
  { code: "PVG", city: "Shanghai", name: "Shanghai Pudong International Airport", country: "Chine" },
  { code: "SHA", city: "Shanghai", name: "Shanghai Hongqiao International Airport", country: "Chine" },
  { code: "CAN", city: "Guangzhou", name: "Guangzhou Baiyun International Airport", country: "Chine" },
  { code: "SZX", city: "Shenzhen", name: "Shenzhen Bao’an International Airport", country: "Chine" },
  { code: "CTU", city: "Chengdu", name: "Chengdu Shuangliu International Airport", country: "Chine" },
  { code: "TFU", city: "Chengdu", name: "Chengdu Tianfu International Airport", country: "Chine" },
  { code: "XIY", city: "Xi’an", name: "Xi’an Xianyang International Airport", country: "Chine" },
  { code: "HGH", city: "Hangzhou", name: "Hangzhou Xiaoshan International Airport", country: "Chine" },
  { code: "CKG", city: "Chongqing", name: "Chongqing Jiangbei International Airport", country: "Chine" },
  { code: "WUH", city: "Wuhan", name: "Wuhan Tianhe International Airport", country: "Chine" },
  { code: "NKG", city: "Nankin", name: "Nanjing Lukou International Airport", country: "Chine" },
  { code: "XMN", city: "Xiamen", name: "Xiamen Gaoqi International Airport", country: "Chine" },
  { code: "KMG", city: "Kunming", name: "Kunming Changshui International Airport", country: "Chine" },
  { code: "TAO", city: "Qingdao", name: "Qingdao Jiaodong International Airport", country: "Chine" },
  { code: "HND", city: "Tokyo", name: "Tokyo Haneda Airport", country: "Japon" },
  { code: "NRT", city: "Tokyo", name: "Narita International Airport", country: "Japon" },
  { code: "KIX", city: "Osaka", name: "Kansai International Airport", country: "Japon" },
  { code: "ITM", city: "Osaka", name: "Osaka Itami Airport", country: "Japon" },
  { code: "NGO", city: "Nagoya", name: "Chubu Centrair International Airport", country: "Japon" },
  { code: "CTS", city: "Sapporo", name: "New Chitose Airport", country: "Japon" },
  { code: "FUK", city: "Fukuoka", name: "Fukuoka Airport", country: "Japon" },
  { code: "OKA", city: "Okinawa", name: "Naha Airport", country: "Japon" },
  { code: "HIJ", city: "Hiroshima", name: "Hiroshima Airport", country: "Japon" },
  { code: "SDJ", city: "Sendai", name: "Sendai Airport", country: "Japon" },
  { code: "LUX", city: "Luxembourg", name: "Aéroport de Luxembourg", country: "Luxembourg" },
  { code: "KUL", city: "Kuala Lumpur", name: "Kuala Lumpur International Airport", country: "Malaisie" },
  { code: "SZB", city: "Kuala Lumpur", name: "Sultan Abdul Aziz Shah Airport", country: "Malaisie" },
  { code: "PEN", city: "Penang", name: "Penang International Airport", country: "Malaisie" },
  { code: "LGK", city: "Langkawi", name: "Langkawi International Airport", country: "Malaisie" },
  { code: "BKI", city: "Kota Kinabalu", name: "Kota Kinabalu International Airport", country: "Malaisie" },
  { code: "KCH", city: "Kuching", name: "Kuching International Airport", country: "Malaisie" },
  { code: "JHB", city: "Johor Bahru", name: "Senai International Airport", country: "Malaisie" },
  { code: "SIN", city: "Singapour", name: "Singapore Changi Airport", country: "Singapour" },
  { code: "XSP", city: "Singapour", name: "Seletar Airport", country: "Singapour" },
  { code: "BKK", city: "Bangkok", name: "Suvarnabhumi Airport", country: "Thaïlande" },
  { code: "DMK", city: "Bangkok", name: "Don Mueang International Airport", country: "Thaïlande" },
  { code: "HKT", city: "Phuket", name: "Phuket International Airport", country: "Thaïlande" },
  { code: "CNX", city: "Chiang Mai", name: "Chiang Mai International Airport", country: "Thaïlande" },
  { code: "KBV", city: "Krabi", name: "Krabi International Airport", country: "Thaïlande" },
  { code: "USM", city: "Koh Samui", name: "Samui Airport", country: "Thaïlande" },
  { code: "HDY", city: "Hat Yai", name: "Hat Yai International Airport", country: "Thaïlande" },
  { code: "UTP", city: "Pattaya", name: "U-Tapao Rayong-Pattaya International Airport", country: "Thaïlande" },
  { code: "CEI", city: "Chiang Rai", name: "Mae Fah Luang-Chiang Rai International Airport", country: "Thaïlande" },
];

export const AIRPORT_COUNTRIES = Array.from(new Set(AIRPORTS.map((airport) => airport.country)));
